name: Blog RSS Feed Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  update-rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Cloud09 Space RSS feed
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.rss.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://cloud09.space/rss
          plugin_rss_limit: 6
          config_timezone: Asia/Shanghai
