name: Metrics Steam
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run on every push on the master branch
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics.plugin.steam.svg
          base: ""
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561199163893956" # Replace with your Steam ID
          plugin_steam_sections: player, recently-played
          plugin_steam_recent_games_limit: 2