name: Metrics AniList
on:
  # Schedule daily updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run on every push on the master branch
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics.plugin.anilist.characters.svg
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: Cloud09Official
          plugin_anilist_sections: characters
          plugin_anilist_limit: 0
          plugin_anilist_limit_characters: 33
